/**
 * @module services/liveShareService
 * @description Real-time collaboration service for Live Share rooms.
 * Handles room messages, file sharing, and room lifecycle management.
 */

import { createItem, listenCollection, setValue } from './realtimeDb';
import { uploadFile } from './storageService';

/** A text message sent in a Live Share room. */
export type RoomMessage = {
  /** Message ID (auto-generated by Firebase). */
  id?: string;
  /** Message text content. */
  content: string;
  /** Send timestamp in milliseconds. */
  timestamp: number;
  /** Display name or ID of the message author. */
  author: string;
  /** Whether this message was sent by an admin. */
  isAdmin?: boolean;
};

/** A file shared in a Live Share room. */
export type RoomFile = {
  /** File ID (auto-generated by Firebase). */
  id?: string;
  /** Original file name. */
  name: string;
  /** Download URL. */
  url: string;
  /** File size in bytes. */
  size: number;
  /** Upload timestamp in milliseconds. */
  timestamp: number;
  /** Entry type marker. */
  type: 'file';
};

/**
 * Builds the database path for a room's messages or files.
 * @internal
 */
const roomPath = (roomId: string, type: 'messages' | 'files') =>
  `liveShare/${roomId}/${type}`;

/**
 * Generates a deterministic admin room ID for a given user.
 *
 * @param userId - The user's unique ID.
 * @returns Admin room ID prefixed with `admin-`.
 */
export const getAdminRoomId = (userId: string) => `admin-${userId}`;

/**
 * Subscribes to real-time message updates in a room.
 *
 * @param roomId - The room identifier.
 * @param onChange - Callback invoked with the latest messages array.
 * @returns Unsubscribe function.
 */
export const listenRoomMessages = (
  roomId: string,
  onChange: (messages: RoomMessage[]) => void
) => {
  return listenCollection<RoomMessage>(roomPath(roomId, 'messages'), onChange);
};

/**
 * Subscribes to real-time file updates in a room.
 *
 * @param roomId - The room identifier.
 * @param onChange - Callback invoked with the latest files array.
 * @returns Unsubscribe function.
 */
export const listenRoomFiles = (
  roomId: string,
  onChange: (files: RoomFile[]) => void
) => {
  return listenCollection<RoomFile>(roomPath(roomId, 'files'), onChange);
};

/**
 * Sends a text message to a room.
 *
 * @param roomId - The room identifier.
 * @param message - The message payload to send.
 * @returns The generated message key.
 */
export const addMessage = async (roomId: string, message: RoomMessage) => {
  return createItem(roomPath(roomId, 'messages'), message);
};

/**
 * Uploads a file to a room and stores its metadata.
 *
 * Uploads the file to Firebase Storage under `live-share/{roomId}/`,
 * then creates a metadata entry in the room's files collection.
 *
 * @param roomId - The room identifier.
 * @param file - The file to upload.
 * @returns The created `RoomFile` metadata.
 */
export const uploadRoomFile = async (roomId: string, file: File) => {
  // Upload to matching storage path
  const uploaded = await uploadFile(`live-share/${roomId}`, file);
  const meta: RoomFile = {
    name: uploaded.name,
    url: uploaded.url || '',
    size: uploaded.size,
    timestamp: Date.now(),
    type: 'file',
  };
  await createItem(roomPath(roomId, 'files'), meta);
  return meta;
};

/**
 * Clears all messages and files in a room without deleting the room itself.
 *
 * @param roomId - The room identifier.
 */
export const clearRoom = async (roomId: string) => {
  await setValue(roomPath(roomId, 'messages'), null);
  await setValue(roomPath(roomId, 'files'), null);
};

/**
 * Permanently deletes a room and all its data.
 *
 * @param roomId - The room identifier.
 */
export const deleteRoom = async (roomId: string) => {
  await setValue(`liveShare/${roomId}`, null);
};
