/**
 * @module services/timelineService
 * @description Service for managing pregnancy/baby timeline events.
 * Supports creating and listening to timeline milestones, checkups, and notes.
 */

import { createItem, listenCollection } from './realtimeDb';

/** Represents a milestone or event on the pregnancy/baby timeline. */
export type TimelineEvent = {
  /** Event ID (auto-generated by Firebase). */
  id?: string;
  /** Event title. */
  title: string;
  /** Event date as ISO string. */
  date: string;
  /** Event description text. */
  description: string;
  /** Type/category of the timeline event. */
  type: 'checkup' | 'milestone' | 'ultrasound' | 'note';
};

/** @internal Realtime Database path for timeline events. */
const TIMELINE_PATH = 'timeline';

/**
 * Subscribes to real-time timeline event updates.
 *
 * @param onChange - Callback invoked with the latest array of events.
 * @returns Unsubscribe function.
 */
export const listenTimeline = (onChange: (events: TimelineEvent[]) => void) => {
  return listenCollection<TimelineEvent>(TIMELINE_PATH, onChange);
};

/**
 * Adds a new event to the timeline.
 *
 * @param event - The timeline event data to create.
 * @returns The generated event key.
 */
export const addTimelineEvent = async (event: TimelineEvent) => {
  return createItem(TIMELINE_PATH, event);
};
