/**
 * @module services/ultrasoundService
 * @description Service for managing ultrasound scan records.
 * Handles image upload to Firebase Storage and metadata storage in Realtime Database.
 */

import { createItem, deleteItem, listenCollection } from './realtimeDb';
import { deleteFile, uploadFile } from './storageService';

/** An ultrasound scan record with image and metadata. */
export type UltrasoundRecord = {
  /** Record ID (auto-generated by Firebase). */
  id?: string;
  /** Download URL of the ultrasound image. */
  url: string;
  /** Scan date as ISO string. */
  date: string;
  /** Optional notes about the scan. */
  notes?: string;
  /** Firebase Storage path for the image file. */
  storagePath?: string;
};

/** @internal Realtime Database path for ultrasound records. */
const ULTRASOUND_PATH = 'ultrasounds';

/**
 * Subscribes to real-time ultrasound record updates.
 *
 * @param onChange - Callback invoked with the latest array of records.
 * @returns Unsubscribe function.
 */
export const listenUltrasounds = (
  onChange: (items: UltrasoundRecord[]) => void
) => {
  return listenCollection<UltrasoundRecord>(ULTRASOUND_PATH, onChange);
};

/**
 * Uploads an ultrasound image and creates a database record.
 *
 * @param file - The ultrasound image file to upload.
 * @param date - The scan date.
 * @param notes - Optional notes about the scan.
 * @returns The created `UltrasoundRecord`.
 */
export const uploadUltrasound = async (
  file: File,
  date: string,
  notes?: string
) => {
  const uploaded = await uploadFile('ultrasounds', file);
  const record: UltrasoundRecord = {
    url: uploaded.url || '',
    date,
    notes,
    storagePath: uploaded.path,
  };
  await createItem(ULTRASOUND_PATH, record);
  return record;
};

/**
 * Deletes an ultrasound record and its associated image from storage.
 *
 * @param record - The ultrasound record to delete.
 */
export const deleteUltrasound = async (record: UltrasoundRecord) => {
  if (record.storagePath) {
    await deleteFile(record.storagePath);
  }
  if (record.id) {
    await deleteItem(ULTRASOUND_PATH, record.id);
  }
};
